language: node_js
env:
  - TEST_SUITE=unit
  - TEST_SUITE=lint
node_js:
  - node
  - lts/*
  - v8
install:
  - npm install -g codecov
  - yarn
script:
  - yarn $TEST_SUITE
  - if [ "$TEST_SUITE" == "unit" ]; then codecov; fi